### ISSUE TITLE
挂第二周的号会有问题，

### ISSUE THREAD

**Issue by westspy** [iBreaker/bjguahao#115]
# date: 挂号日期,如填写latest自动挂最新一天
date: "2019-12-6"

# hospitalId: 医院id
hospitalId: "133"

# departmentId: 科室id
departmentId: "200001349"

select_doctor_one_day 333行，服务器返回系统繁忙的错误。
如果date = 2019-11-25就不会出问题。
用chrome跟踪了一下，才疏学浅没有头绪啊。

**Comment by westspy** [comment]
Traceback (most recent call last):
  File "bjguahao.py", line 655, in <module>
    guahao.run()
  File "bjguahao.py", line 638, in run
    total_fee = self.get_fee(doctor)                                # 获取挂号费,需在获取验证码之前
  File "bjguahao.py", line 404, in get_fee
    doctor_id = str(doctor['doctorId'])
TypeError: 'NoneType' object is not subscriptable

**Comment by westspy** [comment]
找到问题了
