### ISSUE TITLE
关于更新时间没有group属性的问题

### ISSUE THREAD

**Issue by rainmoring** [iBreaker/bjguahao#34]
你好，我今天想直接运行一下脚本看看结果，但是在运行的过程中出现了如下错误：
will@will-VirtualBox:~/bjguahao$ python2.7 bjguahao.py 
 2017-09-05 20:51:48 [info] DebugLevel设置为:2
 2017-09-05 20:51:48 [info] 配置加载完成
Traceback (most recent call last):
  File "bjguahao.py", line 323, in <module>
    guahao.run(config_path)
  File "bjguahao.py", line 278, in run
    self.get_duty_time()
  File "bjguahao.py", line 237, in get_duty_time
    refresh_time = m.group('refreshTime')
AttributeError: 'NoneType' object has no attribute 'group'

所以想问一下这个是我自己的环境哪里配置的不对嘛，还是说哪里有遗漏？
运行环境是ubuntu python2.7

**Comment by iBreaker** [comment]
多试几次也是这样吗？  这个可能是页面没有返回的找到refreshTime，不是配置的问题。

**Comment by rainmoring** [comment]
可能是因为填写的挂号日期不对，我重新将日期修改到还没有放号的时候，现在可以运行了。好像就是没有找到页面的时候就会有这个问题。

**Comment by iBreaker** [comment]
嗯 好的
