### ISSUE TITLE
这段代码是不是应该放到后面，get_patient_id会使用doctor，应该判断doctor是否有效后才能调用get_patient_id吧

### ISSUE THREAD

**Issue by happier2** [iBreaker/bjguahao#35]
https://github.com/iBreaker/bjguahao/blob/27c9cf0c79caab8d718b2c5dc8825de3668d9f1e/bjguahao.py#L297

应该放到最后一个else里面

**Comment by iBreaker** [comment]
放在后面有bug，https://github.com/iBreaker/bjguahao/commit/41718264f2bf2842234a9e3e2da6bef0e3a5011b

**Comment by iBreaker** [comment]
这个是提交说明 

获取病人id的逻辑位置改变到了选择医生之后马上进行病人ID获取（页面逻辑上似乎也是这样的，点击医生，选择就诊人，之后获取验证码），避免造成最后提交时请求头中的referer错误返回非json数据导致挂号失败的问题。

**Comment by happier2** [comment]
但是doctor没有正常值返回时，直接调用self.get_patient_id(doctor)会报错的

**Comment by iBreaker** [comment]
嗯  这两种方法都有bug，你看看是否可以修改

**Comment by mat7213** [comment]
` 2017-09-14 06:32:08 [info] 登陆成功
 2017-09-14 06:32:08 [info] 距离放号时间还有12471.565786秒
 2017-09-14 06:32:08 [info] 程序休眠12411.565786秒后开始运行
 2017-09-14 09:59:00 [info] 开始登陆
 2017-09-14 09:59:00 [debug] post data :{'isAjax': True, 'password': u'pass1234', 'mobileNo': u'15321902091', 'yzm': ''}
 2017-09-14 09:59:00 [debug] response data:{"data":[],"hasError":false,"code":200,"msg":"OK"}
 2017-09-14 09:59:00 [info] 登陆成功
 2017-09-14 09:59:00 [debug] 当前挂号日期: 2017-09-28
 2017-09-14 09:59:00 [debug] post data :{'dutyCode': u'1', 'dutyDate': u'2017-09-28', 'hospitalId': u'133', 'departmentId': u'200001346', 'isAjax': True}
 2017-09-14 09:59:00 [debug] response data:{"data":[{"dutySourceId":47916688,"portrait":" pic/zhuanjia.gif","doctorName":"普通医师","doctorTitleName":"普通医师","skill":"牙龈出血、口臭、牙齿松动移位、洗牙、牙周手术","totalFee":50.0,"remainAvailableNumber":0,"dutySourceStatus":1,"hospitalId":133,"departmentId":"200001346","doctorId":"200352984","drCode":null,"planCode":null,"dutyDate":null,"dutyCode":null,"departmentName":null,"isShowFee":2,"dlDutySources":null,"morningnum":0,"afternoonnum":0,"majorName":null,"majorIntroduce":null,"dldutyDate":null,"dldutyCode":null,"regNo":0}],"hasError":false,"code":200,"msg":"OK"}
 2017-09-14 09:59:00 [info] 当前号余量:
+----------+----------------------------------------------+--------+
| 医生姓名 |                     擅长                     | 号余量 |
+----------+----------------------------------------------+--------+
| 普通医师 | 牙龈出血、口臭、牙齿松动移位、洗牙、牙周手术 |   0    |
+----------+----------------------------------------------+--------+
Traceback (most recent call last):
  File "bjguahao.py", line 323, in <module>
    guahao.run(config_path)
  File "bjguahao.py", line 297, in run
    self.get_patient_id(doctor)         # 3. 获取病人id
  File "bjguahao.py", line 213, in get_patient_id
    addr = self.gen_doctor_url(doctor)
  File "bjguahao.py", line 209, in gen_doctor_url
    str(doctor['dutySourceId']) + ".htm"
TypeError: string indices must be integers, not str`

确实会因为doctor没有正常值时出现问题

**Comment by iBreaker** [comment]
是的，可以修改后提交~
