### ISSUE TITLE
平台挂号的确认步骤，增加了获取手机验证码，求支持~~

### ISSUE THREAD

**Issue by zwgxcs** [iBreaker/bjguahao#37]
2017-09-12 10:51:58 [debug] post data :
Traceback (most recent call last):
  File "bjguahao.py", line 323, in <module>
    guahao.run(config_path)
  File "bjguahao.py", line 305, in run
    sms_code = self.get_sms_verify_code()               # 获取验证码
  File "bjguahao.py", line 261, in get_sms_verify_code
    data = json.loads(response.text)
  File "../lib/python2.7/json/__init__.py", line 339, in loads

**Comment by zwgxcs** [comment]
简单实现的话，可以考虑自动点击发送手机验证码，然后pending，等待手动输入，在继续执行

**Comment by iBreaker** [comment]
你把response.text打印出来看是什么。有验证码自动获取的功能。

**Comment by zwgxcs** [comment]
自动获取验证码的函数应该是有问题的。

self.send_code_url = "http://www.bjguahao.gov.cn/v/sendorder.htm"

这个url感觉没有用对，或者被干掉了。。

**Comment by zwgxcs** [comment]
知道了，机器太快，在get_sms_verify_code前sleep一下就ok了。。不然可能服务器数据还没更新到那一步就收到了sendorder了。
谢谢作者~
