### ISSUE TITLE
获取验证码出错

### ISSUE THREAD

**Issue by zangbianxuegu** [iBreaker/bjguahao#64]
Thu, 01 Nov 2018 08:30:02 connectionpool.py[line:393] DEBUG http://www.bjguahao.gov.cn:80 "POST /v/sendorder.htm HTTP/1.1" 200 24
Thu, 01 Nov 2018 08:30:02 bjguahao.py[line:373] DEBUG {"code":200,"msg":"OK."}
Thu, 01 Nov 2018 08:30:02 bjguahao.py[line:375] INFO 获取验证码成功
验证码: Traceback (most recent call last):
  File "bjguahao.py", line 447, in <module>
    guahao.run()
  File "bjguahao.py", line 431, in run
    sms_code = self.get_sms_verify_code()               # 获取验证码
  File "bjguahao.py", line 377, in get_sms_verify_code
    code = self.imessage.get_verify_code()
  File "/Users/chenzang/workspace/bjguahao/imessage.py", line 91, in get_verify_code
    code = ft.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/chenzang/workspace/bjguahao/imessage.py", line 71, in _get_sms_verify_code
    rec_time = datetime.datetime.fromtimestamp(tm  + OSX_EPOCH)
OSError: [Errno 84] Value too large to be stored in data type

请问这是什么原因？

**Comment by iBreaker** [comment]
系统版本是？

**Comment by zangbianxuegu** [comment]
> 系统版本是？

10.13.6

**Comment by riverchu** [comment]
我也遇到了，Mac版本是10.14.1 ，时间计算的结果超过python数据上界了，可能是版本更新后OSX_EPOCH的值有变化了

**Comment by zzzhouzhong** [comment]
看下imessage.py  70行。可能是不同mac osx系统处理不一样。
#63 
                - rec_time = datetime.datetime.fromtimestamp(tm / 1e9 + OSX_EPOCH)
                + #osx 10.11.6，直接相加即可得正确时间。
                + rec_time = datetime.datetime.fromtimestamp(tm  + OSX_EPOCH)

**Comment by riverchu** [comment]
我也看了，应该是时间精度变化了

**Comment by riverchu** [comment]
遇到这个问题的留一下mac内核版本号吧？ 可以加个判断处理不同版本的时间戳

**Comment by iBreaker** [comment]
push 了最新的，大家看看还有这个问题吗    ps: 我没有测

**Comment by zangbianxuegu** [comment]
@iBreaker 协和的号终于挂上了，这个问题应该好了
