### ISSUE TITLE
mac 获取验证码失败

### ISSUE THREAD

**Issue by scxkd2016** [iBreaker/bjguahao#71]
验证码: Traceback (most recent call last):
  File "/Users/kangduo/Desktop/bjguahao/bjguahao.py", line 447, in <module>
    guahao.run()
  File "/Users/kangduo/Desktop/bjguahao/bjguahao.py", line 431, in run
    sms_code = self.get_sms_verify_code()               # 获取验证码
  File "/Users/kangduo/Desktop/bjguahao/bjguahao.py", line 377, in get_sms_verify_code
    code = self.imessage.get_verify_code()
  File "/Users/kangduo/Desktop/bjguahao/imessage.py", line 94, in get_verify_code
    code = ft.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kangduo/Desktop/bjguahao/imessage.py", line 38, in _get_keyboard_verify_code
    kb = kbhit.KBHit()
  File "/Users/kangduo/Desktop/bjguahao/kbhit.py", line 46, in __init__
    self.new_term = termios.tcgetattr(self.fd)
termios.error: (25, 'Inappropriate ioctl for device')

mac os high Sierra 10.13.4

**Comment by scxkd2016** [comment]
![image](https://user-images.githubusercontent.com/23695444/50502988-5c3b2000-0a9e-11e9-9fe2-aaf3df89c34a.png)
可成功挂号
