### ISSUE TITLE
找不到短信数据库

### ISSUE THREAD

**Issue by ifishing** [iBreaker/bjguahao#73]
验证码: Sun, 10 Feb 2019 00:21:19 imessage.py[line:34] ERROR OperationalError('unable to open database file')
找不到短信数据库
Traceback (most recent call last):
  File "bjguahao.py", line 453, in <module>
    guahao.run()
  File "bjguahao.py", line 437, in run
    sms_code = self.get_sms_verify_code()               # 获取验证码
  File "bjguahao.py", line 381, in get_sms_verify_code
    code = self.imessage.get_verify_code()
  File "/code/OpenSource/bjguahao/imessage.py", line 93, in get_verify_code
    done, not_done = wait([sms, keyboard], timeout=30, return_when=FIRST_COMPLETED)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 301, in wait
    waiter.event.wait(timeout)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by ifishing** [comment]
跟这个issue应该是一样的 https://github.com/iBreaker/bjguahao/issues/59 ，用相同的方法解决。
